### ISSUE TITLE
Pandas / CCTBX compatbility

### ISSUE THREAD

**Issue by stefsmeets** [stefsmeets/topas_tools#6]
There seem to be some compatibility issues with the most recent versions of CCTBX / pandas.

- `cif2topas structure.cif` bugs out with `TypeError: unsupported format string passed to special_op_simlified_term.__format__`
- `topasdiff structure.cif --diff fobs.hkl` gives `TypeError: Index(...) must be called with a collection of some kind, <cctbx_aray_family_flex_ext.miller_index object at ... was passed`

**Comment by stefsmeets** [comment]
Work-around, from line 164 in original code:

```python
if mult < z_order:
    try:
        print("   ' {:5s} {:5s} {:5s}".format(
            *sps.site_symmetry(atom.site).special_op_simplified().terms))
    except Exception:
        print()
else:
    print()
```

Looks like this is the only part affected.

**Comment by shelbygalinat** [comment]
Hi, I think this work around is just for the cif2topas issue (looks like that code is for cif2topas.py). Is there a solution for the Index error with topasdiff?

**Comment by stefsmeets** [comment]
Not from my side. If you post the crash log, I'm happy to point you in the right direction.

**Comment by shelbygalinat** [comment]
Thanks! This is the part of the code that seems to run fine, plus the error I'm getting:

```bash
(topas_tools) shelbygalinat@Shelbys-MacBook-Air-3 0p00 % topasdiff Li6PS5CN_fourier_diff.cif --diff fobs.hkl

structure: topas_cif_out
Number of scatterers: 10
At special positions: 10
Unit cell: (9.8983, 9.8983, 9.8983, 90, 90, 90)
Space group: F -4 3 m (No. 216)
Label, Scattering, Multiplicity, Coordinates, Occupancy, Uiso, Ustar as Uiso
Li1  LI    48 ( 0.3044  0.0253  0.6956) 0.40 0.0499 [ - ]
Li2  LI    24 ( 0.2500  0.0090  0.7500) 0.20 0.0499 [ - ]
P1   P      4 ( 1.0000  0.5000  1.0000) 1.00 0.0616 [ - ]
S1   S     16 ( 0.1259 -0.1259  0.6259) 1.00 0.0688 [ - ]
S2   S      4 ( 1.0000  1.0000  1.0000) 0.58 0.0253 [ - ]
S3   S      4 ( 0.7500  0.7500  0.7500) 0.42 0.0317 [ - ]
C1   C     24 ( 0.0586  0.0000  0.0000) 0.07 0.0499 [ - ]
N1   N     24 ( 0.0586  0.0000  0.0000) 0.07 0.0499 [ - ]
C2   C     16 ( 0.7162  0.7162  0.7162) 0.14 0.0499 [ - ]
N2   N     16 ( 0.7838  0.7838  0.7838) 0.14 0.0499 [ - ]

Loading data: fobs.hkl
     usecols: [0, 1, 2, 3]
      labels: h k l fobs
       shape: (66, 4)

structure: topas_cif_out
Number of scatterers: 10
At special positions: 10
Unit cell: (9.8983, 9.8983, 9.8983, 90, 90, 90)
Space group: F -4 3 m (No. 216)
Label, Scattering, Multiplicity, Coordinates, Occupancy, Uiso, Ustar as Uiso
Li1  LI    48 ( 0.3044  0.0253  0.6956) 0.40 0.0499 [ - ]
Li2  LI    24 ( 0.2500  0.0090  0.7500) 0.20 0.0499 [ - ]
P1   P      4 ( 1.0000  0.5000  1.0000) 1.00 0.0616 [ - ]
S1   S     16 ( 0.1259 -0.1259  0.6259) 1.00 0.0688 [ - ]
S2   S      4 ( 1.0000  1.0000  1.0000) 0.58 0.0253 [ - ]
S3   S      4 ( 0.7500  0.7500  0.7500) 0.42 0.0317 [ - ]
C1   C     24 ( 0.0586  0.0000  0.0000) 0.07 0.0499 [ - ]
N1   N     24 ( 0.0586  0.0000  0.0000) 0.07 0.0499 [ - ]
C2   C     16 ( 0.7162  0.7162  0.7162) 0.14 0.0499 [ - ]
N2   N     16 ( 0.7838  0.7838  0.7838) 0.14 0.0499 [ - ]

Scattering table: xray
Number of scattering types: 5
  Type Number    sf(0)   Gaussians
   S       3     16.00       6
   P       1     15.00       6
   N       2      7.00       6
   C       2      6.00       6
   LI      2      3.00       6
  sf(0) = scattering factor at diffraction angle 0.
Minimum d-spacing: 0.861536
Traceback (most recent call last):
  File "/Users/shelbygalinat/opt/anaconda3/envs/topas_tools/bin/topasdiff", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/shelbygalinat/opt/anaconda3/envs/topas_tools/lib/python3.13/site-packages/topas_tools/topasdiff.py", line 195, in main
    run_script()
    ~~~~~~~~~~^^
  File "/Users/shelbygalinat/opt/anaconda3/envs/topas_tools/lib/python3.13/site-packages/topas_tools/topasdiff.py", line 152, in run_script
    fcalc = list(calc_structure_factors(cif, dmin=dmin, table=table).values())[0]
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shelbygalinat/opt/anaconda3/envs/topas_tools/lib/python3.13/site-packages/topas_tools/blender_mini.py", line 303, in calc_structure_factors
    fcalc, phase = f_calc_structure_factors(
                   ~~~~~~~~~~~~~~~~~~~~~~~~^
        structure, dmin=dmin, scatfact_table=table, return_as="series", **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shelbygalinat/opt/anaconda3/envs/topas_tools/lib/python3.13/site-packages/topas_tools/blender_mini.py", line 266, in f_calc_structure_factors
    fcalc = pd.Series(index=f_calc.indices(), data=np.abs(f_calc.data()))
  File "/Users/shelbygalinat/opt/anaconda3/envs/topas_tools/lib/python3.13/site-packages/pandas/core/series.py", line 490, in __init__
    index = ensure_index(index)
  File "/Users/shelbygalinat/opt/anaconda3/envs/topas_tools/lib/python3.13/site-packages/pandas/core/indexes/base.py", line 7649, in ensure_index
    return Index(index_like, copy=copy)
  File "/Users/shelbygalinat/opt/anaconda3/envs/topas_tools/lib/python3.13/site-packages/pandas/core/indexes/base.py", line 532, in __new__
    raise cls._raise_scalar_data_error(data)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/shelbygalinat/opt/anaconda3/envs/topas_tools/lib/python3.13/site-packages/pandas/core/indexes/base.py", line 5289, in _raise_scalar_data_error
    raise TypeError(
    ...<3 lines>...
    )
TypeError: Index(...) must be called with a collection of some kind, <cctbx_array_family_flex_ext.miller_index object at 0x169a810c0> was passed
(topas_tools) shelbygalinat@Shelbys-MacBook-Air-3 0p00 % 
```

**Comment by stefsmeets** [comment]
Thanks, the issue is in this bit here: `f_calc.indices()`:

https://github.com/stefsmeets/topas_tools/blob/84798a7255f15a8ae6df01a7ab3f98bc916359d1/topas_tools/blender_mini.py#L266-L267

This returns a data structure that pandas does not know how to deal with. It's probably something simple like:

```python
index = [hkl for hkl in f_calc.indices()]
fcalc = pd.Series(index=index, data=np.abs(f_calc.data()))
phase = pd.Series(index=index, data=np.angle(f_calc.data()))
```

Although I guess the `f_calc.data()` might also need to be adapted.

I don't have much time to dive into this at the moment and test it. But feel free to try this and let me know if it works.

**Comment by shelbygalinat** [comment]
I replaced the following lines of code in blender_mini.py

- Original lines 266-267 under def f_calc_structure_factors(structure, **kwargs):
```
fcalc = pd.Series(index=f_calc.indices(), data=np.abs(f_calc.data())) 
phase = pd.Series(index=f_calc.indices(), data=np.angle(f_calc.data()))
```
- Replace with
```
index = [hkl for hkl in f_calc.indices()]
fcalc = pd.Series(index=index, data=np.abs(f_calc.data()))
phase = pd.Series(index=index, data=np.angle(f_calc.data()))
```
- Original line 454 under def m2df(m, data='data', sigmas='sigmas'):
`df = pd.DataFrame(index=m.indices())`
- Replace with
```
index = [hkl for hkl in m.indices()]
df = pd.DataFrame(index=index)
```
- Original line 543 under def reduce_all(df, cell, spgr, dmin=None, reindex=True, verbose=True):
`index = generate_indices(cell, spgr, dmin)`
- Replace with
`index = [hkl for hkl in generate_indices(cell, spgr, dmin)]`
- Original line 545 under def reduce_all
`dfm = dfm.reindex(index=index)`
- Replace with
`dfm = dfm.loc[index] `

This seems to fix most of the issues, but I keep getting a scitbx array_family range error with this line in topasdiff.py:
`df['fdiff'] = df['fobs']/scale - df['fcalc']`

It seems like df[fobs] has a few too many elements in the list of fobs values compared to df[fcalc], so subtracting them is throwing an error. Perhaps the part of the code that "merges" the dataframes so that they have data for identical hkls has an error now due to the index edits? I'm not sure - let me know if you can help!

**Comment by stefsmeets** [comment]
Thanks for the nice work! I will work them into the code when I have time.


> This seems to fix most of the issues, but I keep getting a scitbx array_family range error with this line in topasdiff.py:
> `df['fdiff'] = df['fobs']/scale - df['fcalc']`

This is sort of surprising, because both fobs and fcalc are in the same dataframe, so the lengths must match. Since you are getting a scitbx array_family error, I'm thinking that the types in the dataframe are not entirely correct. Could be that the index edits have some side effects pushing the error down the line.

**Comment by shelbygalinat** [comment]
To clarify, my dataframe after running reduce all looks like this, where fobs and fcalc have identical long lists of values for each row/index. So, the length of the column fobs and fcalc in the dataframe are the same, but there are more items in each list for fobs than for fcalc. My guess is this is not the intended dataframe structure and that each hkl should have just one value for fobs and fcalc, where each row has distinct values. Maybe my updated indexing code accidentally wrote the data to lists within the dataframe instead of items at particular indices in the dataframe, but I'm not sure where. Do you see the problem? This is what 1 row looks like when I print it:
                                                                                                                                                                                                                                                                

> m         d                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               fcalc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             fobs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       phases
> (1, 1, 1)   [6, 12, 6, 24, 12, 6, 24, 24, 12, 6, 24, 24, 24, 12, 6, 24, 24, 8, 24, 24, 24, 48, 24, 24, 48, 48, 24, 24, 48, 48, 48, 24, 48, 8, 24, 24, 24, 48, 24, 24, 48, 48, 24, 24, 48, 8, 24, 24, 24, 48, 24, 24, 48, 8, 24, 24, 24, 48, 24, 8, 24, 24, 24, 8]  5.714786  [22.05443318452373, 90.78929919935675, 7.254996363641633, 21.745166981737334, 62.211776926188286, 6.530976143372513, 39.87642510116906, 7.709238950403764, 13.592010363326755, 43.483530515748456, 19.55046608202167, 0.29839849427284504, 11.053010417545304, 11.885352448998319, 10.336397553857609, 8.675813113989378, 8.808732050427492, 18.750366856885254, 53.128145392288914, 19.722139701770125, 23.038395186909792, 4.63405822449887, 20.972239675320104, 7.900589017148598, 13.988216457984759, 12.378336142448648, 11.470875710268494, 12.447429873897669, 3.5046662890504203, 6.801009075715095, 5.816181177420303, 4.608422690017439, 4.561775691419424, 37.68179432569821, 52.80931045444498, 14.713741386236835, 30.94648971641883, 27.263482899082806, 10.948308071407682, 8.899846464587343, 9.744100394061096, 10.681516806304346, 2.3746345359612353, 19.402662394963752, 9.309722808628571, 34.500568263563395, 23.440829766859945, 14.79083022220249, 20.451348476693838, 6.443434982543668, 8.191183149921212, 9.780657192052795, 7.299858891171948, 14.537270368295726, 7.954489899970587, 10.696990242412193, 20.934072125445738, 6.124700270350055, 6.332586105235114, 15.157029308255549, 10.287301507731604, 4.746446336600647, 6.9565713967949385, 16.594006064394403]  [5.5745, 25.7914, 3.3895, 5.3498, 20.0423, 1.8652, 11.0567, 1.7338, 2.6307, 14.4877, 4.9607, 1.459, 2.7678, 4.1664, 2.6956, 2.3016, 2.1237, 0.6194, 5.0944, 15.531, 5.4987, 6.1307, 1.1138, 6.3999, 2.2747, 3.8679, 3.5774, 3.5503, 3.3444, 1.014, 2.3865, 1.6362, 1.1966, 1.2788, 10.0125, 13.788, 3.8468, 9.5734, 7.6019, 3.3787, 1.2382, 2.6564, 2.9077, 0.7122, 6.4191, 2.5346, 8.5555, 7.0124, 4.7292, 6.215, 1.717, 2.2368, 3.2441, 2.0352, 4.7237, 1.817, 2.5968, 6.9406, 1.5928, 1.6467, 4.4626, 2.8551, 1.2371, 1.903, 4.9331, 1.7864]  [1.2598845162656149e-18, -7.945434988249759e-19, -3.858595526604717e-17, 3.615827776517209e-17, 1.1783184647303911e-18, -2.127294186430049e-17, 5.427676777451886e-18, 1.1224948451471539e-18, 6.772661286961462e-18, 4.528235831231067e-18, 1.8763735360989153e-18, -3.1415926535897922, 5.2123080218907156e-18, 3.4559451269153735e-18, -1.5089986049519926e-17, 1.168185198732905e-18, 6.106850894376773e-18, 2.012089112048167, -1.0653895172973094, 2.1723745951852003, 1.3080603851610002, 3.1265429123322095, 3.125278245646124, -2.388306007596886, 1.2867027870731576, -1.1814386155632841, -2.563551371728493, -1.9464992386256195, 0.2816138571823196, 1.484866936274139, 2.815208553784544, -0.5033761927097904, -1.708492891537255, 1.9556582519066235, 0.0009109771892190496, 0.3259111452949231, -1.250315070588555, 0.09178955286518868, 1.2553425999501313, -0.11943410414162473, 0.4277911750808602, -0.2175251883085128, 2.0811739712647963, 0.49971723818452873, 0.1756244280367923, -1.7792300197126185, 0.8804500497613089, -1.4392538024592956, 3.0784331961235654, 3.12391376299659, -2.4886015493642586, -2.176911967038299, 2.9582057414276925, -1.6722641955637692, 0.41770518922191946, 0.25339520459755427, -0.3773176553518567, 0.741185388230702, -0.5513488284675806, 2.4426096200657486, 2.9379038041624264, 1.6623667429545779, -2.6694137081210716, -1.7771374583933834]

**Comment by stefsmeets** [comment]
I think your analysis is correct! I'm not quite sure where this gets introduced, but I would need to play around with the code a bit. I'm at a workshop this week, I will try to see if I can find some time next week.

**Comment by shelbygalinat** [comment]
I found the issue! Essentially the miller.array objects were staying as scitbx_array_family_flex_ext.double objects instead of being treated as iterable lists. I hard coded this in m2df and f_calc_multiplicities to loop over the miller.array, transform it to a list, and then add to the dataframe. Just to clarify, this code generates a .out file which is then used by superflip to perform the fourier transform and eventually generate the .xplor file that can be opened in VESTA, correct? I haven't successfully installed superflip/FFTW yet, but topasdiff does seem to be successfully generating the .out file now.

Here's the final compiled edits I made, including the ones above:

 in blender_mini.py

Original lines 266-267 under def f_calc_structure_factors(structure, **kwargs):
```
fcalc = pd.Series(index=f_calc.indices(), data=np.abs(f_calc.data())) 
phase = pd.Series(index=f_calc.indices(), data=np.angle(f_calc.data()))
```
Replace with
```
index = [hkl for hkl in f_calc.indices()]
fcalc = pd.Series(index=index, data=np.abs(f_calc.data()))
phase = pd.Series(index=index, data=np.angle(f_calc.data()))
```
Original line 410 under def f_calc_multiplicities
`df['m'] = m.multiplicities().data()`
Replace with
```
    index = [hkl for hkl in m.indices()]
    if m.multiplicities().data():
        mult_list = [] #initialize an empty list for the multiplicities
        for mi in m.multiplicities().data():
            mult_list.append(mi) #iterate over the miller.array. Each mi is a multiplicity, so add each multiplicity value to the new list
    df['m'] = pd.Series(mult_list, index=index) #add each multiplicity value to the data frame
```
Original lines 454-458 under def m2df(m, data='data', sigmas='sigmas'):
```
df = pd.DataFrame(index=m.indices())
 if m.data():
        df[data] = m.data()
    if m.sigmas():
        df[sigmas] = m.sigmas()
```
Replace with
```
    index = [hkl for hkl in m.indices()]
    df = pd.DataFrame(index=index)
    if m.data():
        data_list = [] #initialize an empty list for the data
        for mi in m:
            data_list.append(mi[1]) #iterate over the miller.array. Each mi is a tuple of the structure ((h, k, l), data), so add each data value to the new list
        df[data] = pd.Series(data_list, index=index) #add each hkl, data pair to the data frame
    if m.sigmas():
        data_list = [] #initialize an empty list for the data
        for mi in m:
            data_list.append(mi[1]) #iterate over the miller.array. Each mi is a tuple of the structure ((h, k, l), data), so add each data value to the new list
        df[sigmas] = pd.Series(data_list, index=index) #add each hkl, data pair to the data frame
```
Original line 543 under def reduce_all(df, cell, spgr, dmin=None, reindex=True, verbose=True):
`index = generate_indices(cell, spgr, dmin)`
Replace with
`index = [hkl for hkl in generate_indices(cell, spgr, dmin)]`
Original line 545 under def reduce_all
`dfm = dfm.reindex(index=index)`
Replace with
`dfm = dfm.loc[index] `

**Comment by stefsmeets** [comment]
Nice work! Do you want to make a pull request with your changes?

> Just to clarify, this code generates a .out file which is then used by superflip to perform the fourier transform and eventually generate the .xplor file that can be opened in VESTA, correct?

That's the idea, yes. You can use VESTA or any other software that reads these files.

**Comment by stefsmeets** [comment]
Thanks a bunch for the debugging @shelbygalinat!

I fixed the code and will make a new release in a bit, let me know if you run into any other areas that we missed.

https://github.com/stefsmeets/topas_tools/releases/tag/1.0.2

`pip install topas_tools >= 1.0.2`
